TRUNCATE TABLE demografia;
TRUNCATE TABLE tipo_genero;
TRUNCATE TABLE nacionalidad;

INSERT INTO demografia (id, nombre) VALUES (1, 'Shounen');
INSERT INTO demografia (id, nombre) VALUES (2, 'Seinen');
INSERT INTO demografia (id, nombre) VALUES (3, 'Shoujo');
INSERT INTO demografia (id, nombre) VALUES (4, 'Josei');
INSERT INTO demografia (id, nombre) VALUES (5, 'Kodomo');

INSERT INTO tipo_genero (id, nombre) VALUES (1, 'Acción');
INSERT INTO tipo_genero (id, nombre) VALUES (2, 'Apocalíptico');
INSERT INTO tipo_genero (id, nombre) VALUES (3, 'Aventura');
INSERT INTO tipo_genero (id, nombre) VALUES (4, 'Comedia');
INSERT INTO tipo_genero (id, nombre) VALUES (5, 'Deportes');
INSERT INTO tipo_genero (id, nombre) VALUES (6, 'Drama');
INSERT INTO tipo_genero (id, nombre) VALUES (7, 'Ecchi');
INSERT INTO tipo_genero (id, nombre) VALUES (8, 'Escolar');
INSERT INTO tipo_genero (id, nombre) VALUES (9, 'Fantasía');
INSERT INTO tipo_genero (id, nombre) VALUES (10, 'Gastronomía');
INSERT INTO tipo_genero (id, nombre) VALUES (11, 'Género bélico');
INSERT INTO tipo_genero (id, nombre) VALUES (12, 'Gore');
INSERT INTO tipo_genero (id, nombre) VALUES (13, 'Harem');
INSERT INTO tipo_genero (id, nombre) VALUES (14, 'Hentai');
INSERT INTO tipo_genero (id, nombre) VALUES (15, 'Histórico');
INSERT INTO tipo_genero (id, nombre) VALUES (16, 'Horror');
INSERT INTO tipo_genero (id, nombre) VALUES (17, 'Isekai');
INSERT INTO tipo_genero (id, nombre) VALUES (18, 'Kawaii');
INSERT INTO tipo_genero (id, nombre) VALUES (19, 'Lolicon');
INSERT INTO tipo_genero (id, nombre) VALUES (20, 'Mecha');
INSERT INTO tipo_genero (id, nombre) VALUES (21, 'Misterio');
INSERT INTO tipo_genero (id, nombre) VALUES (22, 'Musical');
INSERT INTO tipo_genero (id, nombre) VALUES (23, 'Parodia');
INSERT INTO tipo_genero (id, nombre) VALUES (24, 'Policial');
INSERT INTO tipo_genero (id, nombre) VALUES (25, 'Psicológico');
INSERT INTO tipo_genero (id, nombre) VALUES (26, 'Romance');
INSERT INTO tipo_genero (id, nombre) VALUES (27, 'Shotacon');
INSERT INTO tipo_genero (id, nombre) VALUES (28, 'Slice of Life');
INSERT INTO tipo_genero (id, nombre) VALUES (29, 'Sobrenatural');
INSERT INTO tipo_genero (id, nombre) VALUES (30, 'Space Opera');
INSERT INTO tipo_genero (id, nombre) VALUES (31, 'Supernatural');
INSERT INTO tipo_genero (id, nombre) VALUES (32, 'Thriller');
INSERT INTO tipo_genero (id, nombre) VALUES (33, 'Tragedia');
INSERT INTO tipo_genero (id, nombre) VALUES (34, 'Yaoi');
INSERT INTO tipo_genero (id, nombre) VALUES (35, 'Yuri');

INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Afganistán','AFGANA','AFG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Albania','ALBANESA','ALB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Alemania','ALEMANA','DEU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Andorra','ANDORRANA','AND');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Angola','ANGOLEÑA','AGO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('AntiguayBarbuda','ANTIGUANA','ATG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('ArabiaSaudita','SAUDÍ','SAU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Argelia','ARGELINA','DZA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Argentina','ARGENTINA','ARG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Armenia','ARMENIA','ARM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Aruba','ARUBEÑA','ABW');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Australia','AUSTRALIANA','AUS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Austria','AUSTRIACA','AUT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Azerbaiyán','AZERBAIYANA','AZE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bahamas','BAHAMEÑA','BHS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bangladés','BANGLADESÍ','BGD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Barbados','BARBADENSE','BRB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Baréin','BAREINÍ','BHR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bélgica','BELGA','BEL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Belice','BELICEÑA','BLZ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Benín','BENINÉSA','BEN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bielorrusia','BIELORRUSA','BLR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Birmania','BIRMANA','MMR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bolivia','BOLIVIANA','BOL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bosnia y Herzegovina','BOSNIA','BIH');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Botsuana','BOTSUANA','BWA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Brasil','BRASILEÑA','BRA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Brunéi','BRUNEANA','BRN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bulgaria','BÚLGARA','BGR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('BurkinaFaso','BURKINÉS','BFA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Burundi','BURUNDÉSA','BDI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Bután','BUTANÉSA','BTN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Cabo Verde','CABOVERDIANA','CPV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Camboya','CAMBOYANA','KHM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Camerún','CAMERUNESA','CMR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Canadá','CANADIENSE','CAN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Catar','CATARÍ','QAT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Chad','CHADIANA','TCD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Chile','CHILENA','CHL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('China','CHINA','CHN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Chipre','CHIPRIOTA','CYP');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Ciudad del Vaticano','VATICANA','VAT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Colombia','COLOMBIANA','COL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Comoras','COMORENSE','COM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Corea del Norte','NORCOREANA','PRK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Corea del Sur','SURCOREANA','KOR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Costa de Marfil','MARFILEÑA','CIV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Costa Rica','COSTARRICENSE','CRI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Croacia','CROATA','HRV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Cuba','CUBANA','CUB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Dinamarca','DANÉSA','DNK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Dominica','DOMINIQUÉS','DMA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Ecuador','ECUATORIANA','ECU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Egipto','EGIPCIA','EGY');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('El Salvador','SALVADOREÑA','SLV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Emiratos Árabes Unidos','EMIRATÍ','ARE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Eritrea','ERITREA','ERI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Eslovaquia','ESLOVACA','SVK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Eslovenia','ESLOVENA','SVN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('España','ESPAÑOLA','ESP');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Estados Unidos','ESTADOUNIDENSE','USA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Estonia','ESTONIA','EST');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Etiopía','ETÍOPE','ETH');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Filipinas','FILIPINA','PHL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Finlandia','FINLANDÉSA','FIN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Fiyi','FIYIANA','FJI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Francia','FRANCÉSA','FRA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Gabón','GABONÉSA','GAB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Gambia','GAMBIANA','GMB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Georgia','GEORGIANA','GEO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Gibraltar','GIBRALTAREÑA','GIB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Ghana','GHANÉSA','GHA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Granada','GRANADINA','GRD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Grecia','GRIEGA','GRC');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Groenlandia','GROENLANDÉSA','GRL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Guatemala','GUATEMALTECA','GTM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Guineaecuatorial','ECUATOGUINEANA','GNQ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Guinea','GUINEANA','GIN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Guinea-Bisáu','GUINEANA','GNB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Guyana','GUYANESA','GUY');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Haití','HAITIANA','HTI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Honduras','HONDUREÑA','HND');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Hungría','HÚNGARA','HUN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('India','HINDÚ','IND');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Indonesia','INDONESIA','IDN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Irak','IRAQUÍ','IRQ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Irán','IRANÍ','IRN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Irlanda','IRLANDÉSA','IRL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Islandia','ISLANDÉSA','ISL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Islas Cook','COOKIANA','COK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Islas Marshall','MARSHALÉSA','MHL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Islas Salomón','SALOMONENSE','SLB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Israel','ISRAELÍ','ISR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Italia','ITALIANA','ITA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Jamaica','JAMAIQUINA','JAM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Japón','JAPONÉSA','JPN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Jordania','JORDANA','JOR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Kazajistán','KAZAJA','KAZ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Kenia','KENIATA','KEN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Kirguistán','KIRGUISA','KGZ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Kiribati','KIRIBATIANA','KIR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Kuwait','KUWAITÍ','KWT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Laos','LAOSIANA','LAO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Lesoto','LESOTENSE','LSO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Letonia','LETÓNA','LVA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Líbano','LIBANÉSA','LBN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Liberia','LIBERIANA','LBR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Libia','LIBIA','LBY');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Liechtenstein','LIECHTENSTEINIANA','LIE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Lituania','LITUANA','LTU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Luxemburgo','LUXEMBURGUÉSA','LUX');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Madagascar','MALGACHE','MDG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Malasia','MALASIA','MYS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Malaui','MALAUÍ','MWI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Maldivas','MALDIVA','MDV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Malí','MALIENSE','MLI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Malta','MALTÉSA','MLT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Marruecos','MARROQUÍ','MAR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Martinica','MARTINIQUÉS','MTQ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Mauricio','MAURICIANA','MUS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Mauritania','MAURITANA','MRT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('México','MEXICANA','MEX');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Micronesia','MICRONESIA','FSM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Moldavia','MOLDAVA','MDA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Mónaco','MONEGASCA','MCO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Mongolia','MONGOLA','MNG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Montenegro','MONTENEGRINA','MNE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Mozambique','MOZAMBIQUEÑA','MOZ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Namibia','NAMIBIA','NAM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Nauru','NAURUANA','NRU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Nepal','NEPALÍ','NPL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Nicaragua','NICARAGÜENSE','NIC');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Níger','NIGERINA','NER');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Nigeria','NIGERIANA','NGA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Noruega','NORUEGA','NOR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Nueva Zelanda','NEOZELANDÉSA','NZL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Omán','OMANÍ','OMN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Países Bajos','NEERLANDÉSA','NLD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Pakistán','PAKISTANÍ','PAK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Palaos','PALAUANA','PLW');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Palestina','PALESTINA','PSE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Panamá','PANAMEÑA','PAN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Papúa Nueva Guinea','PAPÚ','PNG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Paraguay','PARAGUAYA','PRY');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Perú','PERUANA','PER');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Polonia','POLACA','POL');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Portugal','PORTUGUÉSA','PRT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Puerto Rico','PUERTORRIQUEÑA','PRI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Reino Unido','BRITÁNICA','GBR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('RepúblicaCentroafricana','CENTROAFRICANA','CAF');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República Checa','CHECA','CZE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República de Macedonia','MACEDONIA','MKD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República del Congo','CONGOLEÑA','COG');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República Democrática delCongo','CONGOLEÑA','COD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República Dominicana','DOMINICANA','DOM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('República Sudafricana','SUDAFRICANA','ZAF');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Ruanda','RUANDÉSA','RWA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Rumanía','RUMANA','ROU');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Rusia','RUSA','RUS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Samoa','SAMOANA','WSM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('San Cristóbal y Nieves','CRISTOBALEÑA','KNA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('San Marino','SANMARINENSE','SMR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('San Vicente y las Granadinas','SANVICENTINA','VCT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Santa Lucía','SANTALUCENSE','LCA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Santo Tomé y Príncipe','SANTOTOMENSE','STP');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Senegal','SENEGALÉSA','SEN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Serbia','SERBIA','SRB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Seychelles','SEYCHELLENSE','SYC');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Sierra Leona','SIERRALEONÉSA','SLE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Singapur','SINGAPURENSE','SGP');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Siria','SIRIA','SYR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Somalia','SOMALÍ','SOM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Sri Lanka','CEILANÉSA','LKA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Suazilandia','SUAZI','SWZ');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Sudán del Sur','SURSUDANÉSA','SSD');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Sudán','SUDANÉSA','SDN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Suecia','SUECA','SWE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Suiza','SUIZA','CHE');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Surinam','SURINAMESA','SUR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Tailandia','TAILANDÉSA','THA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Tanzania','TANZANA','TZA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Tayikistán','TAYIKA','TJK');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Timor Oriental','TIMORENSE','TLS');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Togo','TOGOLÉSA','TGO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Tonga','TONGANA','TON');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('TrinidadyTobago','TRINITENSE','TTO');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Túnez','TUNECINA','TUN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Turkmenistán','TURCOMANA','TKM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Turquía','TURCA','TUR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Tuvalu','TUVALUANA','TUV');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Ucrania','UCRANIANA','UKR');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Uganda','UGANDÉSA','UGA');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Uruguay','URUGUAYA','URY');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Uzbekistán','UZBEKA','UZB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Vanuatu','VANUATUENSE','VUT');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Venezuela','VENEZOLANA','VEN');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Vietnam','VIETNAMITA','VNM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Yemen','YEMENÍ','YEM');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Yibuti','YIBUTIANA','DJI');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Zambia','ZAMBIANA','ZMB');
INSERT INTO nacionalidad(pais, gentilicio, iso) VALUES ('Zimbabue','ZIMBABUENSE','ZWE');